# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSJbN35brgo3ib_43Ute3bOx3Ubv4qY5
"""

def kasallik_tashxisi (belgi):
  if belgi=="istima":
      return "Parasetamol iching"
  elif belgi=="tish og'rig'i":
     return "Qupen iching"
  elif belgi=="qorin og'rig'i":
     return "Levomitsin"
  elif belgi=="ko'z og'rig'i":
     return "Deksatobrom"
  elif belgi=="tomoq og'rig'i":
     return "Anzibel"
  elif belgi=="bel og'rig'i":
     return "Dyuklofenak"
  elif belgi=="jigar og'rig'i":
     return "Karsil"
  elif belgi=="yurak og'rig'i":
     return "valerianka"
  else:
     return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

def mashhur_futbolchilar (belgi):
  if belgi=="o'zbekiston":
      return "Odil Ahmedov"
  elif belgi=="germaniya":
     return "Gerd Myuller"
  elif belgi=="fransiya":
     return "Zinedin Zidan"
  elif belgi=="italiya":
     return "Djanluiji Buffon"
  elif belgi=="turkiya":
     return "Xoqon Shukur"
  elif belgi=="norvegiya":
     return "Erling Haaland"
  elif belgi=="portugaliya":
     return "Krishtianu Ronaldu"
  elif belgi=="argentina":
     return "Lionel Messi"
  elif belgi=="ispaniya":
     return "Sergio Ramos"
  elif belgi=="gollandiya":
     return "Yohan Kroyf"
  elif belgi=="braziliya":
     return "Pele"
  else:
     return "Googledan qidiring"
belgi=input("Davlat nomini kiriting")
natija=mashhur_futbolchilar(belgi)
print(natija)